### ISSUE TITLE
Create a section to describe how to contribute to the project

### ISSUE THREAD

**Issue by Maykon-JDS** [Maykon-JDS/converter#6]
## Description

We need to create a section in the `README.md` file to provide clear instructions on how to contribute to the project. This will help potential contributors understand how they can get involved and what the process is for submitting changes to the project.

## Tasks

- Add a "Contributing" section in the `README.md` file.
- Provide guidelines for contributing, including:
  - How to clone the repository.
  - How to create a new branch for changes.
  - How to commit and push changes.
  - How to submit a pull request.
- Ensure the instructions are clear and easy to follow.
- Mention any additional rules or code style guidelines (if any).

## Acceptance Criteria

- A new "Contributing" section is added to the `README.md` file.
- The section contains step-by-step instructions on how to contribute.
- The instructions are easy to follow and suitable for new contributors.

**Comment by that-ar-guy** [comment]
hey @Maykon-JDS  can i work on this

**Comment by Maykon-JDS** [comment]
Hi @that-ar-guy. 

Thank you for contributing! Contributions are always welcome 😁
